apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: go-app
spec:
  provider: istio
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-app
  progressDeadlineSeconds: 60
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: go-app
  service:
    port: 80
    targetPort: 8080
    gateways:
    - go-app
    hosts:
    - go-app.kombaraj.com
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 60
    stepWeight: 20
